// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvPOASVT6CF15hwjwx4NgDoTkg8wOD9Pc',
    appId: '1:280911399663:web:7c49dac9ae1fdca143a91a',
    messagingSenderId: '280911399663',
    projectId: 'spoolscout',
    authDomain: 'spoolscout.firebaseapp.com',
    storageBucket: 'spoolscout.firebasestorage.app',
    measurementId: 'G-L6V5NGYDPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZSvp_wsHEd8hkhSNQd4SgiJrrv65PopE',
    appId: '1:280911399663:android:34c336e7df25232543a91a',
    messagingSenderId: '280911399663',
    projectId: 'spoolscout',
    storageBucket: 'spoolscout.firebasestorage.app',
  );
}
